//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorN5.Models.reis.aprendizagem.aulas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fonte
    {
        public int Id { get; set; }
        public string URL { get; set; }
        public int Aula { get; set; }
    }
}
