//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorN5.Models.reis.aprendizagem.exercicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercicio
    {
        public int Id { get; set; }
        public int Dificuldade { get; set; }
        public string Ficheiro { get; set; }
        public int NumeroAlineas { get; set; }
        public string Tipo { get; set; }
        public int Rei { get; set; }
        public int Aula { get; set; }
    }
}
