//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorN5.Models.reis.aprendizagem.exercicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilizadorExercicio
    {
        public int Id { get; set; }
        public int Utilizador { get; set; }
        public int Exercicio { get; set; }
        public Nullable<int> AlineasCorretas { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
