//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorN5.Models.reis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rei
    {
        public int Id { get; set; }
        public string Biografia { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<System.DateTime> DataMorte { get; set; }
        public string Nome { get; set; }
        public string Imagem { get; set; }
    }
}
