//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorN5.Models.reis
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilizadorRei
    {
        public int Id { get; set; }
        public int Utilizador { get; set; }
        public int Rei { get; set; }
        public Nullable<int> Dificuldade { get; set; }
        public Nullable<int> Progresso { get; set; }
        public Nullable<int> BioEstado { get; set; }
    }
}
