//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TutorN5.Models.utilizador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Idade { get; set; }
        public Nullable<int> ProgressoGeral { get; set; }

        [Display(Name="Modo de Interatividade")]
        public Nullable<int> ModoInt { get; set; }
        public Nullable<int> TotalExercicios { get; set; }
        public Nullable<int> ExerciciosPositivos { get; set; }
        public Nullable<int> TotalAlineas { get; set; }
        public Nullable<int> TotalAlineasCorretas { get; set; }
        public Nullable<int> TotalAulas { get; set; }
    }
}
