package client.gui;

import javax.swing.ImageIcon;
import middleware.SO;

/**
 * Secção da aplicação onde demonstramos ao utilizador como o jogo funciona.
 * @author jdc
 * @version 2015.04.13
 */

public class Help extends javax.swing.JInternalFrame {

    public Help() {
        initComponents();
        
        // Imagens
        this.background.setIcon(new ImageIcon(SO.getFancyBackground()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ajuda");
        setPreferredSize(new java.awt.Dimension(843, 569));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("O Jogo . . .");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(38, 22, 127, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Regras");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(377, 258, 63, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>\n<ul>\n<li>Cada questão é sobre um pequeno trecho de música de um minuto complementado com uma imagem;</li>\n<li>Tens até um minuto para responder (ou ignorar);</li>\n<li>Por cada resposta acertada ganhas dois pontos e por cada resposta errada perdes um ponto;</li>\n<li>No final do jogo, ganha o jogador com mais pontos e amealha três pontos adicionais;</li>\n<li>Em caso de empate considera-se o tempo total que os jogadores empatados levaram a responder às questões certas; (apenas certas?)</li>\n<li>Pelo menos um outro jogador terá que aceitar o desafio para que o jogo venha a começar (senão é cancelado);</li>\n<li>Só podes ter um jogo ativo em simultâneo e tendo proposto um desafio não podes jogar desafios de outros enquanto o teu não tiver ocorrido;</li>\n</ul>\n</html>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 270, 612, 230);

        exitButton.setText("Perfil");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(10, 520, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>\nO objetivo do jogo <b>duas ou mais pessoas</b> jogarem numa sessão/desafio de perguntas com escolha de resposta múltipla.<br>\n  O vencedor desse desafio é aquele que acertar mais perguntas (em caso de empate no número de respostas certas desempata-se\npelo tempo total que demorarem a responder às questões certas). No fim de cada jogo, a pontuação obtida é integrada no teu score global.<br>\n  Podes consultar o ranking na <b>secção ranking</b> da aplicação.\n</html>");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(38, 81, 501, 136);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\daniel\\Documents\\GitHub\\QuizClient\\res\\background.jpg")); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(868, 513));
        getContentPane().add(background);
        background.setBounds(0, -40, 930, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
